runtime: nodejs14

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 12345*
  CLOUD_SQL_DATABASE_NAME: banksampah
  CLOUD_SQL_CONNECTION_NAME: test_net

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 1
  max_instances: 5
